# your website url
baseURL = 'https://www.example.com/'
# website title
title = 'Bridget'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
# available options
# * en (powered by Geist)
# * de (powered by Geist)
# * es (powered by Geist)
# * fr (powered by Geist)
# * it (powered by Geist)
# * zh-sg zh-cn (powered by Noto Sans SC)
# * zh-hk zh-tw zh-mo (powered by Noto Sans TC)
# * ja (powered by Noto Sans JP)
# * ko (powered by Noto Sans KR)
defaultContentLanguage = 'en'

# theme as local file
# themesdir = "../.."
# theme = "bridget"

# theme as module
[module]
[[module.imports]]
path = "github.com/Sped0n/bridget"
