# --- REQUIRED -----------------------------------------------------------------

# description of the site (will be placed in meta)
description = "Bridget is a minimal Hugo theme designed for photographers/visual artists."

# resize options for dynamic resolution, please refer to https://gohugo.io/content-management/image-processing/#image-processing-options
loResOpt = "800x webp Lanczos q60"
hiResOpt = "2500x webp Lanczos q75"

# labels (text shown on the UI)
[labels]
next = "next"
prev = "prev"
close = "close"
threshold = "Threshold"
error = "page not found"
loading = "loading..."

# --- OPTIONAL -----------------------------------------------------------------

# whether to use favicon resource links
# generate these with https://realfavicongenerator.net
favicon = true
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = "/dot.svg"
# fallback png favicon for unsupported browsers
svgFaviconFallback = "/dot.png"

# site verification code for Google/Bing/Yandex/Pinterest/Baidu
[verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""
so = ""
sogou = ""

# analytics config
[analytics]
enable = true
# Google Analytics
[analytics.google]
id = ""
# whether to anonymize IP
anonymizeIP = true
# Fathom Analytics
[analytics.fathom]
id = ""
# server url for your tracker if you're self hosting
server = ""
# Baidu Analytics
[analytics.baidu]
id = ""
# Umami Analytics
[analytics.umami]
data_website_id = "942d4c0d-ebd0-4da7-936a-bd278af32e5e"
src = "https://umami.sped0n.com/script.js"
data_host_url = ""
data_domains = "bridget-demo.sped0n.com"
# Plausible Analytics
[analytics.plausible]
data_domain = ""
src = ""
# Cloudflare Analytics
[analytics.cloudflare]
token = ""
# Splitbee Analytics
[analytics.splitbee]
enable = false
# no cookie mode
no_cookie = true
# respect the do not track setting of the browser
do_not_track = true
# token(optional), more info on https://splitbee.io/docs/embed-the-script
data_token = ""
